# 📘 Chapter 1. 통계 기반 자연어처리 개요

자연어처리(Natural Language Processing, NLP)는 컴퓨터가 인간의 언어를 이해하고 해석하도록 만드는 인공지능 분야입니다.

## 🔎 NLP 접근 방식의 역사적 발전

| 시대 | 접근 방식 | 특징 | 예시 |
|------|-----------|-------|------|
| 1세대 | **규칙 기반 (Rule-based NLP)** | 사람이 규칙(문법/패턴)을 정의 | 품사 태깅 규칙, 형태소 사전 |
| 2세대 | **통계 기반 (Statistical NLP)** | 단어의 빈도, 확률, 통계를 활용 | N-gram, TF-IDF, HMM |
| 3세대 | **딥러닝 기반 (Neural NLP)** | 대규모 데이터 + 신경망 활용 | Word2Vec, LSTM, Transformer, BERT |

> ✅ 본 문서에서는 통계 기반 NLP를 집중적으로 다루며, 각 기법이 어떻게 딥러닝의 기반이 되었는지 연결까지 설명합니다.

---

## 🎯 통계 기반 NLP의 핵심 아이디어

> **"언어는 규칙이 아니라 데이터 패턴(recurring patterns)로부터 이해할 수 있다."**

아래는 통계 기반 접근의 핵심 키워드입니다:

- **단어 빈도(Frequency)**: 어떤 단어가 많이 등장하는가?
- **조건부 확률(Conditional Probability)**: 이전 단어가 주어졌을 때 다음 단어가 등장할 확률은?
- **TF-IDF**: 문서에서 중요한 단어는 무엇인가?
- **동시 등장(Co-occurrence)**: 어떤 단어들이 함께 등장하는가?
- **언어 모델(Language Model)**: 문장이 자연스러운가를 수치화하는 모델

---

## 🧠 통계 기반 NLP가 여전히 중요한 이유

| 장점 | 설명 |
|------|------|
| 💡 **해석 가능성** | 결과가 확률/수식으로 표현되어 명확히 설명 가능 |
| ⚡ **계산 속도 빠름** | 딥러닝 없이도 빠르게 결과 생성 |
| 📊 **실무에 적용 용이** | 검색, 추천, 키워드 추출 등에서 여전히 기본 도구로 사용 |

---

# 📘 Chapter 2. 언어모델과 확률, 로그 확률의 의미

통계 기반 자연어처리의 핵심은 **언어를 확률적으로 모델링하는 것**입니다.

---

## 🔎 2.1 언어모델(Language Model)이란?

언어모델(Language Model)은 **문장이나 단어 시퀀스가 등장할 확률을 계산하는 모델**입니다.

### 📌 목표:
> **"문장이 얼마나 자연스러운지"**를 수치화하여 표현

예를 들어, 다음 두 문장 중 어떤 문장이 더 자연스러운지 확률로 판단할 수 있습니다.

- ✅ "오늘 날씨가 정말 좋다" → 높은 확률
- ❌ "정말 날씨가 오늘 좋다" → 낮은 확률

---

## 🔢 2.2 언어모델의 수식적 정의

문장 \( w_1, w_2, \dots, w_n \)의 확률은 다음과 같이 정의됩니다:

\[
P(w_1, w_2, ..., w_n) = P(w_1) \times P(w_2 \mid w_1) \times P(w_3 \mid w_1, w_2) \times \cdots \times P(w_n \mid w_1,...,w_{n-1})
\]

이 식은 실제 계산이 불가능할 정도로 복잡합니다 → 그래서 **N-gram 근사법**을 사용합니다.

---

## 🔢 2.3 N-gram 근사(Language Model Approximation)

| N 값 | 의미 | 고려하는 문맥 | 예시 |
|------|------|---------------|------|
| Unigram (N=1) | 단어 독립 가정 | 없음 | P(오늘) · P(날씨) · P(좋다) |
| Bigram (N=2) | 바로 앞 단어 고려 | 1단어 | P(오늘) · P(날씨|오늘) · P(좋다|날씨) |
| Trigram (N=3) | 앞의 2단어 고려 | 2단어 | P(오늘) · P(날씨|오늘) · P(정말|오늘,날씨) |

### ✅ Bigram 예시:
\[
P(오늘 날씨가 좋다) = P(오늘) \times P(날씨가|오늘) \times P(좋다|날씨가)
\]

---

## 📉 2.4 로그 확률(Log Probability)의 필요성

- 단어의 조건부 확률은 매우 작은 값입니다 (예: 0.001, 0.00001 ...)
- 이런 값들을 곱하면 **0에 매우 가까운 값이 되어 계산 불안정 발생 (Underflow)**
- 이를 해결하기 위해 **로그(log)**를 취합니다.

> ### 📌 로그의 특징:
> \[
> \log(a \times b) = \log a + \log b
> \]
> 곱셈 → 덧셈으로 단순화

### ✅ 로그 값의 해석:
| 로그값 | 의미 |
|--------|------|
| 0에 가까움 | 확률 높음 → 자연스러운 문장 |
| 매우 음수(-∞에 가까움) | 확률 낮음 → 부자연스러운 문장 |

---

## 🔍 2.5 퍼플렉시티(Perplexity, 혼란도)

> 언어모델이 문장을 얼마나 “헷갈려 하는지”를 수치화한 값  
> 낮을수록 좋음 (모델이 문장을 더 잘 설명함)

\[
PP = \exp\left(-\frac{1}{T} \sum_{i=1}^{T} \log P(w_i \mid w_{i-1}) \right)
\]

---

## 📌 정리

| 개념 | 설명 |
|------|------|
| 언어모델 | 문장의 자연스러움을 확률로 표현 |
| N-gram | 과거 N개의 단어만 보고 확률 계산 |
| 로그 확률 | 확률 곱셈의 언더플로 방지를 위해 사용 |
| 퍼플렉시티 | 언어모델 성능 평가 지표 (낮을수록 좋음) |

👇 이제 실제 코드로 Bigram 언어모델을 구현하고 로그 확률 및 퍼플렉시티를 계산해봅니다.

In [44]:
# 📌 Bigram 언어모델 구현 + 로그 확률 + 퍼플렉시티 계산

from collections import Counter
import math

# 샘플 코퍼스 정의
sents = [
    "오늘 날씨가 좋다",
    "오늘 기분이 좋다",
    "내일 날씨가 맑다",
    "내일 기분이 좋다",
]

# 토큰화(문장 시작/끝 토큰 포함)
def tok(s): 
    return s.split()
# "시작/종료 토큰을 사용하는 구조는 전통적인 N-gram 모델부터 최신 GPT, BERT까지 대부분의 NLP 모델에서 사용된다."
corpus = [["<s>"] + tok(s) + ["</s>"] for s in sents]
corpus

[['<s>', '오늘', '날씨가', '좋다', '</s>'],
 ['<s>', '오늘', '기분이', '좋다', '</s>'],
 ['<s>', '내일', '날씨가', '맑다', '</s>'],
 ['<s>', '내일', '기분이', '좋다', '</s>']]

In [48]:

# Unigram / Bigram 카운트
unigrams = Counter(w for sent in corpus for w in sent)
bigrams = Counter((sent[i], sent[i+1]) for sent in corpus for i in range(len(sent)-1))
print(unigrams)
print(bigrams)

Counter({'<s>': 4, '</s>': 4, '좋다': 3, '오늘': 2, '날씨가': 2, '기분이': 2, '내일': 2, '맑다': 1})
Counter({('좋다', '</s>'): 3, ('<s>', '오늘'): 2, ('기분이', '좋다'): 2, ('<s>', '내일'): 2, ('오늘', '날씨가'): 1, ('날씨가', '좋다'): 1, ('오늘', '기분이'): 1, ('내일', '날씨가'): 1, ('날씨가', '맑다'): 1, ('맑다', '</s>'): 1, ('내일', '기분이'): 1})

In [49]:

V = len(unigrams)  # 어휘 수

# Add-1 smoothing 적용한 Bigram 확률
# 항목	의미
# count(prev, curr)	Bigram 빈도
# +1	등장하지 않은 경우라도 최소 1번 등장했다고 가정
# V	전체 단어(어휘) 수
# “어떤 단어가 실제로 나오지 않았더라도, 나올 가능성은 있다”고 가정하는 것
# → 통계적 편향을 줄이고, 모델을 더 일반화시키는 기법
def bigram_prob(prev, curr):
    return (bigrams[(prev, curr)] + 1) / (unigrams[prev] + V)

# 문장 로그확률 계산
def sentence_log_prob(sentence_tokens):
    seq = ["<s>"] + sentence_tokens + ["</s>"]
    log_p = 0.0
    for i in range(len(seq)-1):
        prob = bigram_prob(seq[i], seq[i+1])
        log_p += math.log(prob)
    return log_p

# 퍼플렉시티 계산
def perplexity(sentence_tokens):
    log_p = sentence_log_prob(sentence_tokens)
    T = len(sentence_tokens) + 1  # </s> 포함
    # 자연상수 공식
    return math.exp(-log_p / T)

# 테스트 문장
candidate1 = "오늘 날씨가 맑다".split()
candidate2 = "기분이 내일 좋다".split()

print("문장1:", candidate1)
print("로그확률:", sentence_log_prob(candidate1))
print("퍼플렉시티:", perplexity(candidate1))
print("\n문장2:", candidate2)
print("로그확률:", sentence_log_prob(candidate2))
print("퍼플렉시티:", perplexity(candidate2))

문장1: ['오늘', '날씨가', '맑다']
로그확률: -6.109247582764365
퍼플렉시티: 4.605779351596906

문장2: ['기분이', '내일', '좋다']
로그확률: -8.101677747454572
퍼플렉시티: 7.579289311365564

# 📘 Chapter 3. Bag-of-Words (BoW)

Bag-of-Words는 **문서의 단어 순서는 무시하고**,  
**각 문서에서 단어가 얼마나 자주 등장했는지**만을 기반으로 벡터화하는 가장 기본적인 통계 기반 NLP 기법입니다.

---

## 🔎 3.1 BoW의 핵심 아이디어

| 특징 | 설명 |
|------|------|
| 순서 무시 | 단어의 위치나 순서는 고려하지 않음 |
| 단어 빈도 기반 | 문서에 단어가 몇 번 등장했는지가 중요 |
| 단순하고 빠름 | 머신러닝 모델의 입력으로 사용 가능 |

---

In [19]:
docs = [
    "영화 정말 재미있다",
    "영화 너무 지루하다",
    "배우 연기가 좋다",
]
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# ---------------------------
# 1) 직접 BoW 구현
# ---------------------------
# 단어 추출 (토큰화)
tokens = [doc.split() for doc in docs]
vocab = sorted(set(sum(tokens, [])))  # 전체 단어 사전
print("📌 단어 사전:", vocab)

# BoW 행렬 만들기
bow_matrix = []
for doc in tokens:
    row = [doc.count(word) for word in vocab]
    bow_matrix.append(row)

df_bow_manual = pd.DataFrame(bow_matrix, columns=vocab)
print("\n✅ 직접 구현한 BoW 행렬:")
display(df_bow_manual)

# ---------------------------
# 2) CountVectorizer 사용
# ---------------------------
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(docs)
df_bow_sklearn = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

print("\n✅ CountVectorizer BoW 행렬:")
display(df_bow_sklearn)

📌 단어 사전: ['너무', '배우', '연기가', '영화', '재미있다', '정말', '좋다', '지루하다']

✅ 직접 구현한 BoW 행렬:

   너무  배우  연기가  영화  재미있다  정말  좋다  지루하다
0   0   0    0   1     1   1   0     0
1   1   0    0   1     0   0   0     1
2   0   1    1   0     0   0   1     0

✅ CountVectorizer BoW 행렬:

   너무  배우  연기가  영화  재미있다  정말  좋다  지루하다
0   0   0    0   1     1   1   0     0
1   1   0    0   1     0   0   0     1
2   0   1    1   0     0   0   1     0

# 📘 Chapter 4. TF-IDF 개념과 코드 실습

TF-IDF는 BoW 모델의 단순 빈도 기반 한계를 보완하기 위한 통계 기반 기법으로,  
**문서 내 단어의 빈도(TF)**와 **말뭉치 전체에서의 희소성(IDF)**을 결합해  
단어의 “중요도”를 정량적으로 측정합니다.

---

## 🔎 4.1 TF (Term Frequency)
\[
TF(w,d) = \frac{\text{문서 d 에서의 단어 w 출현 횟수}}{\text{문서 d 전체 단어 수}}
\]

- 문서 내 빈도가 높을수록 값이 큼  
- 자주 등장할수록 그 문서에서 중요하다고 판단  

---

## 🔎 4.2 IDF (Inverse Document Frequency)
\[
IDF(w) = \log\frac{N}{df(w)} \quad
\text{또는 스무딩을 적용해 } \log\frac{1+N}{1+df(w)} + 1
\]

- \(N\): 전체 문서 수  
- \(df(w)\): 단어 w가 등장한 문서 수  
- 흔한 단어(예: “그리고”, “하지만”)는 IDF 값이 낮음

---

## 🔎 4.3 TF-IDF 최종 공식
\[
TF\text{-}IDF(w,d) = TF(w,d) \times IDF(w)
\]

- TF 값이 크고, IDF 값도 크면 → 해당 단어가 그 문서를 대표하는 핵심 단어  
- 흔한 단어(높은 TF, 낮은 IDF)는 가중치가 낮게 조정  

---

## 💡 예시
| 단어 | TF | DF | IDF | TF-IDF |
|------|----|----|------|--------|
| 영화 | 0.2 | 3 | 0.17 | 0.034 |
| 재미있다 | 0.2 | 1 | 1.09 | 0.218 |

👉 “재미있다”는 특정 문서에서만 자주 나타나므로 더 높은 중요도를 가짐

---

## 📊 4.4 TF-IDF 의미 요약
| 항목 | 설명 |
|------|------|
| TF | 문서 내 단어 빈도 |
| IDF | 전체 말뭉치 기준 희소성 |
| TF×IDF | 단어의 문서 특이성 측정 값 |
| 값이 클수록 | 해당 문서 대표 단어 가능성 높음 |

👇 이제 실제 코드를 통해 TF-IDF 벡터화와 단어 중요도 출력을 확인합니다.

In [24]:
import math

docs = [
    "이 영화 정말 재미있다",
    "이 영화 정말 지루하다",
    "배우 연기가 정말 좋다",
]
tokens = [d.split() for d in docs]
# 중복 제외 단어의 길이 
V = sorted(set(sum(tokens, [])))
# docs의 길이
N = len(docs)

# DF 계산
# 단어의 개수 계산
df = {w: sum(1 for doc in tokens if w in doc) for w in V}
def tf(word, doc): 
    return doc.count(word) / len(doc)
def idf(word): 
    return math.log( (N) / (df[word] + 1) ) + 1  # smoothing

# TF-IDF 행렬
X_tfidf = [[tf(w, doc) * idf(w) for w in V] for doc in tokens]
# X_tfidf = []                            # 전체 TF-IDF 행렬 (문서 수 × 어휘 수)

# for doc in tokens:                      # 각 문서에 대해
#     row = []                            # 그 문서의 TF-IDF 벡터
#     for w in V:                         # 어휘집의 각 단어에 대해
#         value = tf(w, doc) * idf(w)     # TF-IDF = TF × IDF
#         row.append(value)               # 열 방향으로 채우기
#     X_tfidf.append(row)                 # 한 문서의 벡터를 행으로 추가

print("Vocab:", V)
print("TF-IDF shape:", (len(X_tfidf), len(V)))

Vocab: ['배우', '연기가', '영화', '이', '재미있다', '정말', '좋다', '지루하다']
TF-IDF shape: (3, 8)

In [21]:
import pandas as pd

In [25]:
pd.DataFrame(X_tfidf, columns=V)

         배우       연기가    영화     이      재미있다        정말        좋다      지루하다
0  0.000000  0.000000  0.25  0.25  0.351366  0.178079  0.000000  0.000000
1  0.000000  0.000000  0.25  0.25  0.000000  0.178079  0.000000  0.351366
2  0.351366  0.351366  0.00  0.00  0.000000  0.178079  0.351366  0.000000

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

vec = TfidfVectorizer(ngram_range=(1,2), min_df=1)
X = vec.fit_transform(docs)
print("Vocab size:", len(vec.get_feature_names_out()))
print("TF-IDF matrix:\n", X.toarray())

Vocab size: 13
TF-IDF matrix:
 [[0.         0.         0.         0.         0.40619178 0.40619178
  0.53409337 0.31544415 0.53409337 0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.40619178 0.40619178
  0.         0.31544415 0.         0.         0.53409337 0.
  0.53409337]
 [0.39687454 0.39687454 0.39687454 0.39687454 0.         0.
  0.         0.2344005  0.         0.39687454 0.         0.39687454
  0.        ]]

## 🔍 출력 해석

- TF-IDF 행렬의 각 값은 “해당 문서에서 그 단어의 중요도”를 나타냅니다.
- 마지막 표에서 합계가 큰 단어일수록 여러 문서에서 의미 있게 등장한 단어입니다.

| 단어 | 의미 |
|------|------|
| 영화 | 모든 문서에 등장, 중요도 중간 |
| 재미있 | 긍정 감정을 나타내는 핵심 단어 |
| 지루하 | 부정 감정 단어 |
| 훌륭하 | 긍정적 강조 단어 |

---

## ⚙️ 실무 팁
- 감정 분석에서는 **TF-IDF + SVM** 조합이 가장 보편적
    - 단어별 피쳐가 생성됨으로 고차원 데이터가 됨으로 트리를 중복으로 사용하는 배깅과 부스팅 모델이 어울리지 않음
- `ngram_range=(1,2)` 로 조절하면 "너무 좋다", "별로 였다" 같은 패턴도 포착 가능
- 학습/평가 분리 시에는 반드시 `fit`은 train 데이터에만 적용 → 데이터 누수 방지

---

# 📘 Chapter 5. N-gram 언어모델 (심화 및 응용)

N-gram 언어모델은 문장의 자연스러움을 수치화하는 통계적 방법입니다.  
딥러닝 기반 언어모델(Word2Vec, LSTM, BERT)의 **출발점**이 되며, "언어를 확률로 이해한다"는 핵심 원리를 담고 있습니다.

---

## 🔎 5.1 N-gram의 개념 요약

| N 값 | 명칭 | 문맥 고려 범위 | 예시 |
|------|------|----------------|------|
| 1 | Unigram | 없음 | P(오늘), P(날씨), P(좋다) |
| 2 | Bigram | 앞 1단어 | P(날씨 | 오늘), P(좋다 | 날씨) |
| 3 | Trigram | 앞 2단어 | P(정말 | 오늘, 날씨) |

**Bigram 확률 공식:**
\[
P(w_n | w_{n-1}) = \frac{\text{count}(w_{n-1}, w_n)}{\text{count}(w_{n-1})}
\]

---

## ⚠ 문제점: 확률이 0이 되는 경우
- 훈련 데이터에 등장하지 않은 단어쌍은 확률이 0 → 전체 문장 확률이 0
- 해결 방법: **Add-1 Smoothing (Laplace Smoothing)**

\[
P(w_n | w_{n-1}) = \frac{\text{count}(w_{n-1}, w_n) + 1}{\text{count}(w_{n-1}) + V}
\]
- \( V \): 전체 단어 수

---

## 🔢 5.2 Perplexity (혼란도)
언어모델의 성능을 평가하는 지표. **낮을수록 좋다**.

\[
PP = \exp\left(-\frac{1}{T} \sum_{i=1}^{T} \log P(w_i | w_{i-1})\right)
\]

---

👇 아래 코드에서:
- Bigram 카운트 & 확률 계산
- 로그 확률과 퍼플렉시티 비교
- 자연스러운 문장 vs 비자연스러운 문장 구분

In [1]:
# 📌 Bigram Language Model 심화 구현 + Perplexity 비교 실습

from collections import Counter
import math
import pandas as pd

# 훈련 말뭉치 (실제 형태소 기반이라 가정)
corpus_sentences = [
    "오늘 날씨 가 좋다",
    "오늘 기분 이 좋다",
    "내일 날씨 가 맑다",
    "기분 이 매우 좋다",
    "날씨 가 아주 좋다",
]

# ✅ 토큰화: 띄어쓰기 기준
def tokenize(sentence):
    return sentence.split()

# 문장에 시작/끝 토큰 추가
corpus = [["<s>"] + tokenize(sent) + ["</s>"] for sent in corpus_sentences]

# Unigram, Bigram 카운트
unigrams = Counter(w for sent in corpus for w in sent)
bigrams = Counter((sent[i], sent[i+1]) for sent in corpus for i in range(len(sent)-1))
print(unigrams)
print(bigrams)

Counter({'<s>': 5, '</s>': 5, '좋다': 4, '날씨': 3, '가': 3, '오늘': 2, '기분': 2, '이': 2, '내일': 1, '맑다': 1, '매우': 1, '아주': 1})
Counter({('좋다', '</s>'): 4, ('날씨', '가'): 3, ('<s>', '오늘'): 2, ('기분', '이'): 2, ('오늘', '날씨'): 1, ('가', '좋다'): 1, ('오늘', '기분'): 1, ('이', '좋다'): 1, ('<s>', '내일'): 1, ('내일', '날씨'): 1, ('가', '맑다'): 1, ('맑다', '</s>'): 1, ('<s>', '기분'): 1, ('이', '매우'): 1, ('매우', '좋다'): 1, ('<s>', '날씨'): 1, ('가', '아주'): 1, ('아주', '좋다'): 1})

In [2]:

V = len(unigrams)  # 어휘 수

# 📌 Laplace Smoothing 적용한 Bigram 확률
def bigram_prob(prev, curr):
    return (bigrams[(prev, curr)] + 1) / (unigrams[prev] + V)

# 📌 문장 로그확률 및 Perplexity 계산
def sentence_log_prob(tokens):
    seq = ["<s>"] + tokens + ["</s>"]
    log_p = 0.0
    for i in range(len(seq)-1):
        p = bigram_prob(seq[i], seq[i+1])
        log_p += math.log(p)
    return log_p

def perplexity(tokens):
    log_p = sentence_log_prob(tokens)
    T = len(tokens) + 1  # </s> 포함
    # 자연상수 계산식
    return math.exp(-log_p / T)

# ✅ 테스트 문장
test_sentences = [
    "오늘 날씨 가 맑다",
    "기분 이 내일 좋다",
    "날씨 가 아주 좋다",
]

# 결과 출력
results = []
for s in test_sentences:
    tokens = tokenize(s)
    lp = sentence_log_prob(tokens)
    pp = perplexity(tokens)
    results.append([s, lp, pp])

df_results = pd.DataFrame(results, columns=["문장", "로그확률", "퍼플렉시티"])
display(df_results)
print("\n✅ Perplexity가 낮을수록 문장이 자연스럽다고 판단됨")

           문장       로그확률     퍼플렉시티
0  오늘 날씨 가 맑다  -8.888972  5.916792
1  기분 이 내일 좋다 -10.047669  7.459838
2  날씨 가 아주 좋다  -8.511678  5.486747

✅ Perplexity가 낮을수록 문장이 자연스럽다고 판단됨

## 🔍 결과 해석

| 문장 | 로그확률 | 퍼플렉시티 |
|------|----------|------------|
| "오늘 날씨 가 맑다" | -X.XX | 낮음 ✅ 자연스러운 문장 |
| "기분 이 내일 좋다" | -Y.YY | 높음 ❌ 비자연스러운 어순 |
| "날씨 가 아주 좋다" | -Z.ZZ | 낮음 ✅ 자주 등장한 패턴 |

- **로그확률(Log Probability)**이 *덜 음수일수록* (값이 클수록) 해당 문장이 훈련 데이터와 유사함
- **Perplexity**는 **낮을수록** 모델이 문장을 잘 예측했다는 의미
  - PP < 50 → 매우 자연스러운 문장
  - PP > 500 → 부자연스럽거나 훈련 데이터와 달라 모델이 “혼란스러워함”

---

## 🧠 정리

| 개념 | 설명 |
|------|------|
| N-gram | 이전 N-1개의 단어만 보고 다음 단어 확률 예측 |
| Add-1 Smoothing | 등장하지 않은 단어쌍의 확률을 0이 되지 않도록 조정 |
| 로그확률 | 확률 곱셈을 덧셈으로 바꿔 계산 안정성 확보 |
| Perplexity | 언어모델이 문장을 얼마나 잘 예측하는지 측정하는 지표 (낮을수록 좋음) |

---

📌 **다음 챕터에서는 동시출현(Co-occurrence)과 PMI(점별 상호정보량)를 다룹니다.**  
이는 Word2Vec, GloVe 등 분산 표현 모델의 뿌리가 되는 핵심 개념입니다.

👇 계속해서 Chapter 6을 생성합니다.

# 📘 Chapter 6. 동시출현 행렬(Co-occurrence Matrix)과 PMI

자연어에서 단어는 *독립적으로 의미를 갖지 않고*, **문맥(Context)** 속에서 의미를 갖습니다.  
**"You shall know a word by the company it keeps"** – Firth (1957)

---

## 🔎 6.1 Co-occurrence Matrix란?

> **특정 단어 기준으로** 주변 윈도우(window) 안에서 **어떤 단어가 함께 등장했는지 빈도를 기록한 행렬**입니다.

### 📌 예시 문장:
"오늘 날씨가 매우 좋다"
"오늘 기분이 정말 좋다"
"내일 날씨가 조금 맑다"

- 윈도우 크기 = 1 (좌우 한 단어만 본다고 가정)
- "날씨가" 주변에 나타나는 단어는 ["오늘", "매우", "내일", "조금"]

➡ 이 정보를 기반으로 **단어 간 연관성**을 수치화할 수 있음

---

## 📊 6.2 Co-occurrence Matrix vs TF-IDF vs N-gram

| 기법 | 특징 | 문맥 반영 | 방법 |
|------|------|-----------|------|
| BoW | 단어 빈도 | ❌ | 단순 카운트 |
| TF-IDF | 희소성 반영 | ❌ | 빈도 × 역문서빈도 |
| N-gram | 단어 순서 반영 | ✅ 제한적 | 조건부 확률 |
| **Co-occurrence** | 의미 관계 반영 | ✅ | 주변 단어 함께 등장 빈도 |

---

## 🔢 6.3 PMI(Pointwise Mutual Information)

동시출현 빈도만으로는 정보가 부족합니다.  
**PMI는 두 단어가 “우연히 함께 등장한 것인지”, 아니면 “의미적으로 연관이 있는지”를 측정합니다.**

\[
PMI(w, c) = \log \frac{P(w, c)}{P(w) \cdot P(c)}
\]

- \(P(w, c)\): w와 c가 함께 등장할 확률
- \(P(w)\), \(P(c)\): 각 단어의 단독 등장 확률

### ✅ 해석:
| PMI 값 | 의미 |
|--------|------|
| **높음** | 의미적으로 강하게 연결된 단어 |
| 0 근처 | 무관한 단어 |
| **음수** | 함께 등장할 가능성이 낮음 (우연이 아님) |

---

## ✨ PPMI (Positive PMI)
- **음수 PMI는 잘 사용되지 않음**
- 음수를 0으로 처리한 것이 **PPMI** (Pointwise Positive Mutual Information)

\[
PPMI(w, c) = \max(PMI(w, c), 0)
\]

➡ Word2Vec, GloVe와 같은 임베딩의 핵심 개념!

---

🧪 아래 코드에서 실제 Co-occurrence Matrix를 생성하고 PPMI를 계산해봅니다.

In [3]:
# 동시출현 행렬(Co-occurrence) + PMI + PPMI 계산 실습

import math
from collections import defaultdict
import pandas as pd

sentences = [
    "오늘 날씨 가 매우 좋다",
    "오늘 기분 이 정말 좋다",
    "내일 날씨 가 조금 맑다",
    "기분 이 매우 나쁘다",
]

# ✅ 윈도우 크기 설정 (예: 좌우 2단어까지 포함)
window_size = 1

# ✅ 토큰화
tokens = [s.split() for s in sentences]
vocab = sorted(set(sum(tokens, [])))
vocab_index = {word: idx for idx, word in enumerate(vocab)}
vocab_index

{'가': 0,
 '기분': 1,
 '나쁘다': 2,
 '날씨': 3,
 '내일': 4,
 '맑다': 5,
 '매우': 6,
 '오늘': 7,
 '이': 8,
 '정말': 9,
 '조금': 10,
 '좋다': 11}

In [4]:

# ✅ Co-occurrence Matrix 초기화
co_matrix = [[0] * len(vocab) for _ in range(len(vocab))]
co_matrix

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [5]:

# ✅ 윈도우 기반 동시출현 카운트
for sent in tokens:
    for idx, word in enumerate(sent):
        center_idx = vocab_index[word]
        # 윈도우 범위 지정
        start = max(0, idx - window_size)
        end = min( len(sent), idx + window_size + 1 )
        # 주변 단어 카운트
        for i in range(start, end):
            if i != idx:
                context = sent[i]
                context_idx = vocab_index[context]
                co_matrix[center_idx][context_idx] += 1

# ✅ DataFrame 변환
df_co = pd.DataFrame(co_matrix, index=vocab, columns=vocab)
print("✅ 동시출현 행렬(Co-occurrence Matrix):")
df_co

✅ 동시출현 행렬(Co-occurrence Matrix):

     가  기분  나쁘다  날씨  내일  맑다  매우  오늘  이  정말  조금  좋다
가    0   0    0   2   0   0   1   0  0   0   1   0
기분   0   0    0   0   0   0   0   1  2   0   0   0
나쁘다  0   0    0   0   0   0   1   0  0   0   0   0
날씨   2   0    0   0   1   0   0   1  0   0   0   0
내일   0   0    0   1   0   0   0   0  0   0   0   0
맑다   0   0    0   0   0   0   0   0  0   0   1   0
매우   1   0    1   0   0   0   0   0  1   0   0   1
오늘   0   1    0   1   0   0   0   0  0   0   0   0
이    0   2    0   0   0   0   1   0  0   1   0   0
정말   0   0    0   0   0   0   0   0  1   0   0   1
조금   1   0    0   0   0   1   0   0  0   0   0   0
좋다   0   0    0   0   0   0   1   0  0   1   0   0

In [11]:
sum(sum(co_matrix, []))

30

In [12]:

# ✅ PMI & PPMI 계산
total_count = sum(sum(row) for row in co_matrix)
p_word = [sum(row) / total_count for row in co_matrix]  # P(w)
p_context = [sum(co_matrix[i][j] for i in range(len(vocab))) / total_count for j in range(len(vocab))]  # P(c)
print(total_count)
print(p_word)
print(p_context)

30
[0.13333333333333333, 0.1, 0.03333333333333333, 0.13333333333333333, 0.03333333333333333, 0.03333333333333333, 0.13333333333333333, 0.06666666666666667, 0.13333333333333333, 0.06666666666666667, 0.06666666666666667, 0.06666666666666667]
[0.13333333333333333, 0.1, 0.03333333333333333, 0.13333333333333333, 0.03333333333333333, 0.03333333333333333, 0.13333333333333333, 0.06666666666666667, 0.13333333333333333, 0.06666666666666667, 0.06666666666666667, 0.06666666666666667]

In [13]:

# ✅ PMI 계산 함수
def calc_pmi(i, j):
    p_wc = co_matrix[i][j] / total_count
    if p_wc == 0:
        return 0
    return math.log2(p_wc / (p_word[i] * p_context[j]) + 1e-12)  # log2 사용

# ✅ PPMI 행렬
ppmi_matrix = [[max(calc_pmi(i, j), 0) for j in range(len(vocab))] for i in range(len(vocab))]
# ppmi_matrix = []  # 최종적으로 담을 2차원 리스트 (행렬)

# # i번째 단어 (행)
# for i in range(len(vocab)):
#     row = []  # i행에 해당하는 리스트 생성
    
#     # j번째 단어 (열)
#     for j in range(len(vocab)):
#         pmi = calc_pmi(i, j)  # PMI 계산
#         ppmi_value = max(pmi, 0)  # 음수면 0, 양수면 그대로 유지(=PPMI)
#         row.append(ppmi_value)  # 열에 추가
    
#     ppmi_matrix.append(row)  # 완성된 열을 행렬에 추가
df_ppmi = pd.DataFrame(ppmi_matrix, index=vocab, columns=vocab)
print("\n✅ PPMI 행렬:")
df_ppmi.style.background_gradient(cmap='Blues')

✅ PPMI 행렬:

# 📘 Chapter 7. LSA (Latent Semantic Analysis, 잠재 의미 분석)

LSA는 문서(Document)와 단어(Word) 사이의 **잠재적인 의미 구조(latent semantic structure)**를 추출하는 통계 기반 기법입니다.

---

## 🔎 7.1 왜 LSA가 필요한가?

- BoW, TF-IDF는 **단어 간의 의미적 유사성을 반영하지 못함**
  - 예: "영화"와 "필름"은 같은 뜻이지만 다른 벡터로 표현됨
- LSA는 **단어-문서 행렬을 SVD 분해**하여
  - **단어 간 의미 관계**
  - **문서의 잠재적 주제(Topic)**
  를 파악할 수 있음

---

## 📌 7.2 LSA의 핵심 아이디어

1. **TF-IDF 행렬 생성**
2. **SVD (Singular Value Decomposition)** 적용하여 차원 축소
3. **잠재 의미 공간(Latent Semantic Space)**에서 단어/문서를 표현

\[
\text{TF-IDF Matrix } A = U \Sigma V^T
\]
| 요소 | 설명 |
|------|------|
| \(U\) | 단어 벡터 |
| \(\Sigma\) | 중요도(특잇값, singular values) |
| \(V^T\) | 문서 벡터 |

> ✅ 큰 의미를 가지는 성분(특잇값)을 남기고, 나머지를 제거 → **노이즈 제거 + 주제 추출**

---

## 🎯 7.3 LSA의 효과

| 효과 | 설명 |
|------|------|
| 차원 축소 | 벡터 공간의 차원을 줄여 계산 효율 증가 |
| 의미 유추 | "영화"와 "필름"처럼 비슷한 문맥의 단어가 가까운 벡터로 이동 |
| 토픽 분석 | 문서를 주제별로 분류 가능 |

---

## 📌 예시 데이터
우리의 문서:

# 🔷 TruncatedSVD란?
| 항목       | 설명                                                  |
| -------- | --------------------------------------------------- |
| 정식 명칭    | Truncated Singular Value Decomposition (절단된 특잇값 분해) |
| 핵심 목적    | 고차원 희소 행렬을 낮은 차원으로 압축하면서 데이터의 구조적 의미(잠재 의미)를 유지     |
| 주요 사용 분야 | 자연어 처리(NLP), 추천 시스템, 의미 분석(LSA), 잠재 토픽 분석           |
| 입력 데이터   | **희소 행렬 지원 (예: TF-IDF)** → PCA는 기본적으로 밀집행렬만 가능      |


🧠 직관적 이해

문서-단어 TF-IDF 행렬은 수천×수만 차원의 엄청 큰 행렬

대부분의 값은 0 → 희소 행렬

TruncatedSVD를 사용하면 문서를 50~300차원 정도의 의미 벡터로 요약 가능

같은 토픽의 문서는 벡터 공간에서 가깝게 위치하게 됨 → 유사도 기반 NLP에 활용

In [43]:
# LSA를 통한 의미 공간 분석 (SVD 사용)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
import pandas as pd
from konlpy.tag import Okt

# ✅ 형태소 분석기 준비
okt = Okt()

def okt_tokenizer(text):
    return [word for word, pos in okt.pos(text, stem=True)
            if pos in ["Noun", "Adjective", "Verb"]]

# ✅ 샘플 문서
docs = [
    "이 영화 정말 재미있다",
    "배우 연기가 뛰어나다",
    "이 영화 별로다",
    "지루한 영화는 보기 어렵다",
    "정말 훌륭한 연출이었다",
    "연기가 별로라서 지루했다"
]

# ✅ TF-IDF 벡터화
vectorizer = TfidfVectorizer(
    tokenizer=okt_tokenizer,
    ngram_range=(1,1),
    min_df=1,
    max_df=0.9,
    sublinear_tf=True,
    smooth_idf=True,
    norm='l2'
)

X_tfidf = vectorizer.fit_transform(docs)

# ✅ LSA 적용 (SVD 기반 차원 축소)
# n_components는 잠재된 의미 차원의 수
lsa = TruncatedSVD(n_components=2, random_state=42)
X_lsa = lsa.fit_transform(X_tfidf)

# ✅ 결과 출력
df_lsa = pd.DataFrame(X_lsa, columns=["Topic1", "Topic2"])
df_lsa["문서"] = docs
display(df_lsa)

# ✅ 단어 의미 공간 확인
terms = vectorizer.get_feature_names_out()
components = lsa.components_

df_terms = pd.DataFrame(components.T, index=terms, columns=["Topic1", "Topic2"])
print("\n✅ 단어들의 의미 좌표(Topic Space):")
display(df_terms.sort_values("Topic1", ascending=False).head(10))

c:\Users\ekfla\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

     Topic1    Topic2              문서
0  0.657545 -0.549734    이 영화 정말 재미있다
1  0.216826  0.629844     배우 연기가 뛰어나다
2  0.807468 -0.163849        이 영화 별로다
3  0.530649  0.134956  지루한 영화는 보기 어렵다
4  0.170168 -0.421917    정말 훌륭한 연출이었다
5  0.604051  0.591663   연기가 별로라서 지루했다

✅ 단어들의 의미 좌표(Topic Space):

        Topic1    Topic2
영화    0.493535 -0.202689
별로    0.464354  0.190336
이     0.448914 -0.289080
지루하다  0.328677  0.317544
연기    0.253216  0.516909
정말    0.217880 -0.352804
재미있다  0.216556 -0.257161
보기    0.165433  0.059760
어렵다   0.165433  0.059760
배우    0.073409  0.302884

# 📘 Chapter 8. 통계 기반 NLP의 한계와 딥러닝 기반 확장

자연어처리는 처음에는 **BoW, TF-IDF, N-gram, PMI** 같은 통계 기반 방법으로 시작되었지만,
언어의 복잡성과 문맥성을 충분히 반영하지 못하는 한계가 있었습니다.
이러한 한계는 **Word2Vec → RNN/LSTM → Transformer → BERT → GPT**로 발전하게 된 직접적인 원인이 되었습니다.

---

## 🔴 8.1 통계 기반 NLP의 한계

### ① **문맥(Context)을 반영하지 못함**
- 단어의 순서나 위치 고려 X
- "재미있다"와 "재미없다"는 완전히 다른 뜻임에도 벡터 공간에서 거리가 가까울 수 있음

### ② **표현의 희소성 (Sparsity)**
- 단어가 많아질수록 벡터 차원 폭발(=차원의 저주)
- 대부분의 값이 0인 **희소 행렬(Sparse Matrix)**

### ③ **단어 간 의미적 유사성 부족**
- TF-IDF: 단어의 중요도만 계산, 의미는 반영 X
- "영화"와 "영화관"은 다른 단어로 완전히 분리됨

### ④ **확률 기반 모델의 데이터 의존성**
- N-gram: N이 커질수록 데이터 부족 문제 발생
- 3-gram 이상의 모델은 사실상 학습 불가능 수준

### ⑤ **Out-of-Vocabulary(OOV) 문제**
- 학습에 등장하지 않은 단어는 처리 불가능

---

## ✅ 8.2 이러한 한계를 극복한 딥러닝의 등장

| 세대 | 모델 | 핵심 개념 | 해결한 문제 |
|------|------|-----------|-------------|
| **1세대 임베딩** | Word2Vec, GloVe | 분산 표현(Distributed Representation) | 단어 의미 벡터화, 유사도 반영 |
| **2세대 시퀀스 모델** | RNN, LSTM | 순차적 문맥 이해 | 단어 순서 반영 |
| **3세대 어텐션 기반** | Transformer | 전 문맥(Self-Attention) | 긴 문장 이해, 병렬 처리 |
| **4세대 사전학습 언어모델** | BERT, GPT | 대규모 데이터 + Pretraining | 문맥 기반 양방향 의미 이해, 문장 생성 가능 |

---

## 📌 8.3 통계 기반 → 딥러닝 기반으로의 흐름

### 🔹 Word2Vec (Skip-Gram / CBOW)
- PMI 행렬을 **신경망 구조로 근사**하여 단어 의미를 학습
- "king - man + woman = queen" → 단어 간 관계까지 학습 가능

### 🔹 RNN, LSTM
- 단어 순서를 반영하여 문맥 기반 학습 가능
- 긴 문장에서 정보 손실 문제 해결(LSTM의 장기 의존성)

### 🔹 Transformer
- Self-Attention으로 **문장 전체를 한 번에 보고 의미를 계산**
- 병렬 처리 가능 → 학습 속도 대폭 향상

### 🔹 BERT / GPT
- BERT: 문맥을 양방향(Bidirectional)으로 이해
- GPT: 이전 단어를 기반으로 다음 단어 생성(Generative)

---

## 🧠 8.4 한계 비교 요약

| 기준 | 통계 기반 (TF-IDF, N-gram) | 딥러닝 기반 (Word2Vec, BERT) |
|------|--------------------------|-----------------------------|
| 문맥 이해 | ❌ 불가능 | ✅ 가능 (Self-Attention) |
| 의미 학습 | ❌ 단순 빈도 | ✅ 벡터 공간에서 의미 유추 |
| 차원 | 고차원 희소 | 저차원 밀집(Dense) |
| 성능 | 제한적 | 매우 높은 성능 |
| 학습 데이터 | 소량 | 대규모 데이터 활용 가능 |
| 확장성 | 낮음 | 매우 높음 |

---

## 🚀 8.5 정리 & 다음 단계로의 연결

✅ **통계 기반 NLP는 언어의 기본 패턴을 이해하기에 매우 중요**  
✅ 하지만 현실 언어의 복잡성과 문맥성은 통계 방식만으로 해결 불가  
➡ **딥러닝 기반 언어모델이 등장하여 이 문제를 해결**

---

## 🔮 8.6 다음에 학습할 내용 (딥러닝 기반 NLP 구조)

| 모델 | 핵심 |
|------|------|
| **Word2Vec, GloVe** | 의미 기반 단어 벡터 |
| **LSTM** | 순차적 의존성 |
| **Transformer** | 병렬 학습 + 전체 문맥 |
| **BERT / GPT** | 사전학습 기반 문맥 이해 모델 |

> **즉, 지금까지 배운 통계 기반 기법은 딥러닝 NLP의 기반이며, 다음 단계로 자연스럽게 확장됩니다.**

---

📌 **다음 진도 제안**
1. Word2Vec 내부 동작 이해 + 구현
2. RNN/LSTM 기반 감성 분석
3. Transformer & Self-Attention 시각화
4. BERT 기반 한국어 감정 분류 모델

👉 어떤 주제부터 진행할까요?

In [15]:
corpus = [
    "영화 정말 재미있다",
    "영화 조금 지루하다",
    "배우 연기가 정말 좋다",
    "스토리가 지루하고 전개가 느리다",
    "음악이 정말 아름답다",
    "연출이 참 좋다",
    "정말 뛰어난 연기와 음악",
    "별로 재미없다",
    "평범하지만 무난한 영화",
    "정말 별로다"
]

In [ ]:
# TD-IDF와 코사인 유사도를 이용한 질의의 유사도 검색

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

tfidf = TfidfVectorizer(tokenizer=lambda s:s.split(), lowercase=False)
X = tfidf.fit_transform(corpus)  # (문서 x 단어)

query = "배우 연기가 좋다"
qv = tfidf.transform([query])
# ravel() = 다차원 배열을 1차원으로 평평하게 만드는 NumPy 함수이며, 자연어 처리에서 벡터 간 유사도 계산 결과를 다룰 때 매우 자주 사용됩니다.
sims = cosine_similarity(qv, X).ravel()
# argsort() 함수는 배열의 값을 정렬했을 때 그 정렬 순서를 만드는 "인덱스"를 반환하는 함수입니다.
rank = sims.argsort()[::-1]

print("질의:", query)
for i in rank[:5]:
    print(f"{i:02d} | 점수={sims[i]:.4f} | {corpus[i]}")

질의: 배우 연기가 좋다
02 | 점수=0.9409 | 배우 연기가 정말 좋다
05 | 점수=0.2654 | 연출이 참 좋다
08 | 점수=0.0000 | 평범하지만 무난한 영화
09 | 점수=0.0000 | 정말 별로다
06 | 점수=0.0000 | 정말 뛰어난 연기와 음악

In [18]:
sims

array([0.        , 0.        , 0.94092304, 0.        , 0.        ,
       0.26542299, 0.        , 0.        , 0.        , 0.        ])

In [19]:
# -*- coding: utf-8 -*-
# 코사인 유사도로 "사용자 질문"과 "FAQ 질문"을 비교해 가장 유사한 답을 찾는 간단한 시스템
# 필요 패키지: scikit-learn

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import re
from konlpy.tag import Komoran

komoran = Komoran()
# 유지할 품사 설정 (명사, 동사, 형용사)
include_pos = ['NNG', 'NNP', 'VV', 'VA']
# -----------------------------
# 1) 데이터: (질문, 답변) 쌍
# -----------------------------
FAQ = [
    ("환불은 어떻게 하나요?", "주문 상세 페이지에서 '환불 신청' 버튼을 눌러 접수하실 수 있습니다."),
    ("배송 기간은 얼마나 걸리나요?", "일반 배송은 2~3일, 도서산간 지역은 최대 5일까지 소요됩니다."),
    ("해외 배송도 가능한가요?", "현재 해외 배송은 지원하지 않습니다."),
    ("회원 탈퇴는 어디에서 하나요?", "설정 > 계정 관리 > 회원 탈퇴 메뉴에서 진행하실 수 있습니다."),
    ("비밀번호를 잊어버렸어요", "로그인 화면의 '비밀번호 재설정' 링크를 통해 재설정 가능합니다."),
    ("주문 취소는 어떻게 하죠?", "상품이 배송 준비 전 상태라면 주문 상세 페이지에서 취소가 가능합니다."),
    ("영수증 발급이 가능한가요?", "마이페이지 > 주문 내역에서 영수증 출력이 가능합니다."),
    ("교환/반품은 가능한가요?", "수령일로부터 7일 이내, 미사용/미훼손 제품에 한해 가능합니다."),
]

questions = [q for q, _ in FAQ]
answers   = [a for _, a in FAQ]

# --------------------------------------
# 2) 전처리(간단): 한글/영문/숫자 띄어쓰기 기준 토큰화
#    - 불용어/형태소분석 미사용(의존도↓, 즉시 실행 목적)
# --------------------------------------
def simple_tokenize(text: str) -> list:
    tokens = komoran.pos(text)
    # 지정된 POS만 필터링
    meaningful_tokens = [word for word, pos in tokens if pos in include_pos]
    return meaningful_tokens

# --------------------------------------
# 3) 벡터라이저: TF-IDF (1~2그램) + 대소문자 유지(한글엔 무의미)
# --------------------------------------
vectorizer = TfidfVectorizer(
    tokenizer=simple_tokenize,          # 위 토크나이저 사용
    lowercase=False,
    ngram_range=(1, 2),                 # 1그램 + 2그램(질문 패턴 잡기)
    min_df=1
)

faq_matrix = vectorizer.fit_transform(questions)  # (FAQ개수 x 단어수) 희소행렬

# --------------------------------------
# 4) 검색 함수: 코사인 유사도 → 상위 K개 & 임계치
# --------------------------------------
def retrieve_answer(user_query: str, top_k: int = 3, threshold: float = 0.25):
    """
    user_query: 사용자 질문 (문자열)
    top_k: 상위 몇 개 결과를 보고할지
    threshold: 가장 높은 유사도가 이 값보다 작으면 '적절한 FAQ 없음' 처리
    """
    q_vec = vectorizer.transform([user_query])
    sims = cosine_similarity(q_vec, faq_matrix).ravel()  # (FAQ개수,)
    rank_idx = sims.argsort()[::-1]

    best_idx = rank_idx[0]
    best_score = float(sims[best_idx])

    if best_score < threshold:
        return {
            "found": False,
            "best_score": best_score,
            "message": "FAQ에서 적절한 답변을 찾지 못했습니다. 운영자에게 연결할까요?",
            "candidates": [
                {"question": questions[i], "answer": answers[i], "score": float(sims[i])}
                for i in rank_idx[:top_k]
            ]
        }

    return {
        "found": True,
        "best_question": questions[best_idx],
        "best_answer": answers[best_idx],
        "best_score": best_score,
        "candidates": [
            {"question": questions[i], "answer": answers[i], "score": float(sims[i])}
            for i in rank_idx[:top_k]
        ]
    }

# --------------------------------------
# 5) 테스트
# --------------------------------------
tests = [
    "환불하려면 어떻게 해요?",
    "비번을 잊어버렸습니다",
    "배송은 보통 며칠이나 걸리는지?",
    "해외도 보내주나요?",
    "교환은 며칠 안에 가능한가요?",
    "구매 내역 영수증 출력 가능?"
]

for t in tests:
    res = retrieve_answer(t, top_k=3, threshold=0.25)
    print(f"\n[사용자 질문] {t}")
    if res["found"]:
        print(f"→ 매칭 질문: {res['best_question']} (score={res['best_score']:.3f})")
        print(f"→ 답변: {res['best_answer']}")
    else:
        print(f"→ {res['message']} (최고 유사도={res['best_score']:.3f})")
        print("  유사 후보 상위 3개:")
        for c in res["candidates"]:
            print(f"   - {c['question']} (score={c['score']:.3f})")

[사용자 질문] 환불하려면 어떻게 해요?
→ 매칭 질문: 환불은 어떻게 하나요? (score=1.000)
→ 답변: 주문 상세 페이지에서 '환불 신청' 버튼을 눌러 접수하실 수 있습니다.

[사용자 질문] 비번을 잊어버렸습니다
→ 매칭 질문: 비밀번호를 잊어버렸어요 (score=0.447)
→ 답변: 로그인 화면의 '비밀번호 재설정' 링크를 통해 재설정 가능합니다.

[사용자 질문] 배송은 보통 며칠이나 걸리는지?
→ 매칭 질문: 배송 기간은 얼마나 걸리나요? (score=0.743)
→ 답변: 일반 배송은 2~3일, 도서산간 지역은 최대 5일까지 소요됩니다.

[사용자 질문] 해외도 보내주나요?
→ 매칭 질문: 해외 배송도 가능한가요? (score=0.461)
→ 답변: 현재 해외 배송은 지원하지 않습니다.

[사용자 질문] 교환은 며칠 안에 가능한가요?
→ 매칭 질문: 교환/반품은 가능한가요? (score=0.577)
→ 답변: 수령일로부터 7일 이내, 미사용/미훼손 제품에 한해 가능합니다.

[사용자 질문] 구매 내역 영수증 출력 가능?
→ 매칭 질문: 영수증 발급이 가능한가요? (score=0.577)
→ 답변: 마이페이지 > 주문 내역에서 영수증 출력이 가능합니다.

c:\Users\ekfla\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [ ]:
# -*- coding: utf-8 -*-
"""
NSMC(네이버 영화리뷰) - TF-IDF → TruncatedSVD(LSA) → SVC (Pipeline 미사용 버전)
- 데이터: data/ratings_train.txt, data/ratings_test.txt
- 형태소 분석: Komoran
"""

import os, re, time
import pandas as pd
from konlpy.tag import Komoran
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# -----------------------------
# 1) 데이터 로드
# -----------------------------
TRAIN_PATH = "data/ratings_train.txt"
TEST_PATH  = "data/ratings_test.txt"

def load_nsmc(path):
    df = pd.read_csv(path, sep="\t")
    df["document"] = df["document"].astype(str).apply(lambda s: re.sub(r"\s+", " ", s).strip())
    df = df[df["document"].str.len() > 0]
    df = df.dropna(subset=["label"])
    df["label"] = df["label"].astype(int)
    return df

train = load_nsmc(TRAIN_PATH)
test  = load_nsmc(TEST_PATH)
X_train, y_train = train["document"].tolist()[:5000], train["label"].values[:5000]
X_test, y_test   = test["document"].tolist()[:5000],  test["label"].values[:5000]
print(f"Train: {len(train):,}  /  Test: {len(test):,}")

# -----------------------------
# 2) Komoran 토크나이저
# -----------------------------
komoran = Komoran()
INCLUDE_POS = {"NNG", "NNP", "VV", "VA"}

def komoran_tokenize(text):
    text = re.sub(r"\s+", " ", text).strip()
    return [w for (w, p) in komoran.pos(text, flatten=True) if p in INCLUDE_POS]

print("[Tokenizer] Komoran with POS filter:", sorted(INCLUDE_POS))

# -----------------------------
# 3) TF-IDF 벡터화
# -----------------------------
tfidf = TfidfVectorizer(
    tokenizer=komoran_tokenize,
    lowercase=False,
    ngram_range=(1, 2),
    min_df=5,
    max_df=0.8
)

print("\n[1단계] TF-IDF 변환 중...")
t0 = time.time()
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)
t1 = time.time()
print(f"TF-IDF 완료 ({t1 - t0:.2f}s)")
print(f"TF-IDF shape: {X_train_tfidf.shape}")

Train: 150,000  /  Test: 50,000
[Tokenizer] Komoran with POS filter: ['NNG', 'NNP', 'VA', 'VV']

[1단계] TF-IDF 변환 중...

c:\Users\ekfla\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

TF-IDF 완료 (9.60s)
TF-IDF shape: (50000, 12079)

In [7]:

# -----------------------------
# 4) TruncatedSVD (LSA)
# -----------------------------
svd = TruncatedSVD(n_components=200, random_state=42)
print("\n[2단계] TruncatedSVD 적용 중...")
X_train_svd = svd.fit_transform(X_train_tfidf)
X_test_svd  = svd.transform(X_test_tfidf)
t2 = time.time()
print(f"SVD 완료 ({t2 - t1:.2f}s)")
print(f"SVD shape: {X_train_svd.shape}")

[2단계] TruncatedSVD 적용 중...
SVD 완료 (1.10s)
SVD shape: (50000, 200)

In [8]:

# -----------------------------
# 5) StandardScaler (평균 0, 표준편차 1)
# -----------------------------
scaler = StandardScaler(with_mean=True)
print("\n[3단계] 표준화 중...")
X_train_scaled = scaler.fit_transform(X_train_svd)
X_test_scaled  = scaler.transform(X_test_svd)
t3 = time.time()
print(f"Scaling 완료 ({t3 - t2:.2f}s)")

[3단계] 표준화 중...
Scaling 완료 (0.06s)

In [ ]:

# -----------------------------
# 6) SVC 학습
# -----------------------------
svc = SVC(kernel="linear", C=1.0, random_state=42)
print("\n[4단계] SVC 학습 중...")
svc.fit(X_train_scaled, y_train)
t4 = time.time()
print(f"SVC 학습 완료 ({t4 - t3:.2f}s)")

[4단계] SVC 학습 중...

In [ ]:

# -----------------------------
# 7) 평가
# -----------------------------
print("\n[5단계] 예측 및 평가")
y_pred = svc.predict(X_test_scaled)
acc = accuracy_score(y_test, y_pred)
print(f"\n[Test Accuracy] {acc:.4f}")
print("\n[Classification Report]")
print(classification_report(y_test, y_pred, digits=4))
print("\n[Confusion Matrix]")
print(confusion_matrix(y_test, y_pred))

# -----------------------------
# 8) 샘플 예측
# -----------------------------
samples = [
    "진짜 재미있고 감동적이었어요",
    "완전 별로… 돈 아까움",
    "배우 연기가 좋고 음악도 최고!",
    "스토리가 지루하고 전개가 엉망이다"
]
samples_tfidf = tfidf.transform(samples)
samples_svd = svd.transform(samples_tfidf)
samples_scaled = scaler.transform(samples_svd)
pred = svc.predict(samples_scaled)

print("\n[Sample Predictions]")
for s, p in zip(samples, pred):
    print(f"  ({p}) {s}")

print(f"\n총 실행 시간: {time.time() - t0:.2f}s")

[5단계] 예측 및 평가

[Test Accuracy] 0.7472

[Classification Report]
              precision    recall  f1-score   support

           0     0.7118    0.8232    0.7635      2478
           1     0.7948    0.6725    0.7285      2522

    accuracy                         0.7472      5000
   macro avg     0.7533    0.7479    0.7460      5000
weighted avg     0.7536    0.7472    0.7458      5000


[Confusion Matrix]
[[2040  438]
 [ 826 1696]]

[Sample Predictions]
  (1) 진짜 재미있고 감동적이었어요
  (0) 완전 별로… 돈 아까움
  (1) 배우 연기가 좋고 음악도 최고!
  (0) 스토리가 지루하고 전개가 엉망이다

총 실행 시간: 19.09s